name: Build and Deploy appsvc
on:
  push:
    branches:
    - main
    paths-ignore:
    - '**/*.md'
    - '**/*.gitignore'
    - '**/*.gitattributes'
  workflow_dispatch:
    branches:
    - main
    paths-ignore:
    - '**/*.md'
    - '**/*.gitignore'
    - '**/*.gitattributes'

env:
  AZURE_WEBAPP_NAME: devex-agent1
  AZURE_WEBAPP_PACKAGE_PATH: ./published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  PROJECT_PATH: src/MinimalApiSample/MinimalApiSample.csproj
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
  DOTNET_MULTILEVEL_LOOKUP: 0
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 🧰 Setup .NET Core SDK ${{ env.DOTNET_CORE_VERSION }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: ♻️ Restore packages
      run: dotnet restore "${{ env.PROJECT_PATH }}"
    - name: ⚒️ Build app
      run: dotnet build "${{ env.PROJECT_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-restore /p:SourceRevisionId=${{ github.sha }}
    - name: 🧪 Test app
      run: dotnet test "${{ env.PROJECT_PATH }}" --no-build
    - name: 🖨️ Publish app for deploy
      run: dotnet publish "${{ env.PROJECT_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: ⬆️ Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    needs: build
    name: Deploy to production
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    # Download artifacts
    - name: ⬇️ Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: webapp

    # Login to Azure
    - name: 🔐 Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.DEVX_AGENT1_CLIENTID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 

    # Deploy to App Service Linux
    - name: 🎛️ Deploy to Azure WebApp
      id: deploy_production
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: .
        
    # Logout of Azure
    - name: 🔐 Azure Logout
      if: always()
      run: |
        az logout
